export type WikiSectionId = 'basics' | 'resources' | 'growth' | 'evolution' | 'hosts' | 'prestige' | 'faq'

export interface WikiSection {
  id: WikiSectionId
  title: string
  summary: string
}

export interface WikiEntry {
  id: string
  type: 'article' | 'faq'
  section: WikiSectionId
  title: string
  summary: string
  keywords: string[]
  content: string[]
}

export const wikiSections: WikiSection[] = [
  { id: 'basics', title: 'Basics', summary: 'Core rules, screen roles, and the main loop that drives each run.' },
  { id: 'resources', title: 'Resources', summary: 'What the game tracks, what each abbreviation means, and how progression currencies differ.' },
  { id: 'growth', title: 'Growth', summary: 'Passive income, generator scaling, upgrades, and the host defenses that interrupt them.' },
  { id: 'evolution', title: 'Evolution', summary: 'Strains, core attributes, and skill unlocks that shape the organism build.' },
  { id: 'hosts', title: 'Hosts', summary: 'How stage progression works and what completing each host does for the run.' },
  { id: 'prestige', title: 'Prestige', summary: 'Spore Release, Genetic Memory, and what persists after a reset.' },
  { id: 'faq', title: 'FAQ', summary: 'Quick answers to common progression, locking, and interface questions.' },
]

export const wikiEntries: WikiEntry[] = [
  {
    id: 'how-the-game-works',
    type: 'article',
    section: 'basics',
    title: 'How The Game Works',
    summary: 'Gather biomass, grow passive income, evolve your organism, consume 11 hosts across escalating complexity, and reset for permanent power.',
    keywords: ['loop', 'biomass', 'progression', 'host', 'prestige'],
    content: [
      'Click ABSORB to gather biomass manually at the start of a run.',
      'Spend biomass on generator modules and upgrades to increase passive production.',
      'Clearing hosts advances the run through 11 stages of escalating complexity.',
      'Host clears unlock strains, mutation points, skills, zones, and active attacks.',
      'Each host has unique mechanics: zones, defense profiles, seasonal cycles, rival networks, and more.',
      'Later, Spore Release resets the run in exchange for permanent Genetic Memory and unlocks advanced features.',
    ],
  },
  {
    id: 'main-screens',
    type: 'article',
    section: 'basics',
    title: 'What Each Screen Does',
    summary: 'Terminal is moment-to-moment growth, Evolution is build crafting, and Spore is meta progression.',
    keywords: ['terminal', 'evolution', 'spore', 'screens'],
    content: [
      'Terminal is the active run screen. You gather biomass, buy generators, fight host defenses, and advance stages here.',
      'Evolution is where you spend mutation points, select a strain, and buy stat-gated skills.',
      'Spore is the prestige and meta-progression area. It will be the place to release spores and gain Genetic Memory.',
      'System Logs toggles the observation log panel. On desktop it appears as a footer row below the terminal. On mobile it opens a collapsible card showing the last 12 log entries.',
    ],
  },
  {
    id: 'resource-abbreviations',
    type: 'article',
    section: 'resources',
    title: 'Resource Abbreviations',
    summary: 'The command center uses short labels for common resources and rates.',
    keywords: ['bpc', 'bps', 'ep', 'ltb', 'signal', 'abbreviations'],
    content: [
      'BPC means Biomass Per Click.',
      'BPS means Biomass Per Second.',
      'STAGE marks your current host in the campaign sequence (1-11).',
      'LTB means Lifetime Biomass produced in the current run.',
      'Mutation Points are earned by clearing hosts and are spent on core stats.',
      'Signal is a prestige-layer resource (Run 2+) used for bonus production and special actions.',
      'Enzymes fuel Active Attacks (Stage 4+).',
    ],
  },
  {
    id: 'biomass-and-memory',
    type: 'article',
    section: 'resources',
    title: 'Biomass And Genetic Memory',
    summary: 'Biomass powers your current run. Genetic Memory will be the permanent reward from prestige.',
    keywords: ['biomass', 'genetic memory', 'prestige', 'gamma'],
    content: [
      'Biomass is your main currency. You use it to buy generators, upgrades, and later skills.',
      'Lifetime Biomass is tracked separately from your current biomass. It drives prestige rewards and run analytics.',
      'Genetic Memory is the future prestige currency. It will persist across runs and permanently increase production.',
    ],
  },
  {
    id: 'generators-and-upgrades',
    type: 'article',
    section: 'growth',
    title: 'Generators And Upgrades',
    summary: 'Generators create passive biomass over time. Upgrades are one-time purchases that permanently improve a run.',
    keywords: ['generator', 'upgrade', 'cost scaling', 'passive', 'tier'],
    content: [
      '8 generator tiers: Hyphae Strand → Mycelial Mat → Rhizomorph Cord → Sporocarp Cluster → Fruiting Canopy → Decomposer Bloom → Subterranean Nexus → Planetary Membrane.',
      'Each generator produces biomass automatically every tick.',
      'Generator costs scale upward based on how many of that generator you already own.',
      'Higher tiers unlock based on stage progression and ownership of previous tiers.',
      '9 Upgrades available: 3 early-game (Tiers 1-3) and 6 for higher tiers (5-8), plus 2 late-game click upgrades.',
      'Upgrades are bought once per run and permanently affect production or clicking until reset.',
    ],
  },
  {
    id: 'host-defense-events',
    type: 'article',
    section: 'growth',
    title: 'Host Defense Events',
    summary: 'Hosts fight back with temporary penalties that disrupt your production.',
    keywords: ['drought', 'beetle', 'defense', 'penalty', 'grindable'],
    content: [
      'Defense events are temporary penalties triggered by the current host.',
      'Event frequency and severity scale with stage progression.',
      'From Stage 2 onward, the colony can forecast the next likely defense event before it hits.',
      'Resilience reduces the severity of these penalties, and some resilience skills improve that further.',
      'Stage 4+ hosts feature grindable events that reward enzyme reserves.',
      'Stage 10+ introduces tier-2 events and multi-front pressure.',
    ],
  },
  {
    id: 'countermeasures',
    type: 'article',
    section: 'growth',
    title: 'Countermeasures',
    summary: 'Six specialized countermeasures provide tiered protection against defense events (one per run).',
    keywords: ['countermeasure', 'moisture buffer', 'chitin lattice', 'enzyme suppressor', 'thermal regulator', 'signal jammer', 'spore shield'],
    content: [
      'You may equip ONE countermeasure per run. Choose wisely based on the current host\'s defense profile.',
      'Each countermeasure provides FULL coverage (70% mitigation) for its primary events and PARTIAL coverage (30% mitigation) for secondary events.',
      '',
      'MOISTURE BUFFER — Hydric reserves for thermal and desiccation threats:',
      '  Full: Drought, Desiccation Pulse',
      '  Partial: Cold Snap, Antifungal Exudates',
      '',
      'CHITIN LATTICE — Structural reinforcement against physical disruption:',
      '  Full: Beetle Disruption, Insect Vector Swarm',
      '  Partial: Lignin Fortification, Spore Predation',
      '',
      'ENZYME SUPPRESSOR — Chemical defense neutralization:',
      '  Full: Antifungal Exudates, Microbial Rivalry, Nutrient Sequestration',
      '  Partial: Viral Hijack, Root Allelopathy',
      '',
      'THERMAL REGULATOR — Metabolic heat distribution:',
      '  Full: Cold Snap, Thermal Stratification, UV Surge',
      '  Partial: Desiccation Pulse, Ecosystem Feedback',
      '',
      'SIGNAL JAMMER — Mask colony signature from immune detection:',
      '  Full: Immune Response, Spore Competition, Ecosystem Feedback',
      '  Partial: Viral Hijack, Microbial Rivalry',
      '',
      'SPORE SHIELD — Reproductive tissue protection:',
      '  Full: Spore Predation, Lignin Fortification, Root Allelopathy',
      '  Partial: Insect Vector Swarm, Nutrient Sequestration',
      '',
      'Resilience stat provides additional mitigation (+5% per point).',
      'Maximum mitigation capped at 90% — some penalty always reaches the colony.',
    ],
  },
  {
    id: 'active-attacks',
    type: 'article',
    section: 'growth',
    title: 'Active Attacks',
    summary: 'Spend enzyme reserves to launch targeted assaults on specific host zones (Stage 4+).',
    keywords: ['enzyme', 'attack', 'active', 'reserves', 'zones'],
    content: [
      'Active attacks unlock at Stage 4 (The Rotting Elm).',
      'Enzyme reserves build passively over time up to a cap of 100.',
      'Spend enzymes to launch an attack on the currently active zone.',
      'Active attacks provide a temporary BPS bonus while active.',
      'Cost varies by host and zone type (some zones are cheaper or more expensive to attack).',
      'Enzymes can also be gained by successfully countering defense events.',
      'Strategic use of active attacks can significantly accelerate zone compromise.',
    ],
  },
  {
    id: 'strains-and-stats',
    type: 'article',
    section: 'evolution',
    title: 'Strains And Stats',
    summary: 'After clearing the first host you choose a strain, then shape the run further with Virulence, Resilience, and Complexity.',
    keywords: ['strain', 'parasite', 'symbiote', 'saprophyte', 'virulence', 'resilience', 'complexity', 'soft cap', 'synergy'],
    content: [
      'Parasite favors clicking with Hemorrhagic Burst (periodic massive click multipliers). Virulence is the aligned stat.',
      'Symbiote removes click income and provides Mycorrhizal Network pulses (periodic BPS bonuses). Complexity is the aligned stat.',
      'Saprophyte is a balanced hybrid with Decomposition Loop (recovers biomass from expired events). Resilience is the aligned stat.',
      'Virulence improves click power (+15% per point). Threshold bonus at 3+ points.',
      'Resilience reduces defense penalty severity (+8% mitigation per point).',
      'Complexity improves passive production (+5% per point) and upgrade effectiveness (+2% per point).',
      'Stat Soft Caps: Points beyond 3 have diminishing returns (65% effectiveness per overage point).',
      'Strain Synergy: Stats aligned with your strain get +35% effectiveness. Opposed stats get -30%.',
      'Saprophyte Hybrid Bonus: Distribute points across 2+ stats to unlock a 20% hybrid multiplier.',
    ],
  },
  {
    id: 'skills',
    type: 'article',
    section: 'evolution',
    title: 'Skills',
    summary: 'Skills are biomass-purchased perks unlocked by stage and stat thresholds.',
    keywords: ['skills', 'skill tree', 'requirements', 'purchase'],
    content: [
      'Skills unlock once you reach Stage 3.',
      'Each skill belongs to one stat branch and requires a minimum rank in that stat.',
      'Skills cost biomass (not mutation points) and scale in price.',
      'Virulence skills: Enzymatic Breakdown (rank 1), Acidic Secretion (rank 3), Hemorrhagic Spread (rank 5).',
      'Resilience skills: Chitin Shell (rank 1), Dormancy Protocol (rank 3), Spore Hardening (rank 5).',
      'Complexity skills: Quorum Recursion (rank 1), Signal Amplification (rank 3), Distributed Cognition (rank 5).',
      'Purchased skills permanently affect the current run until prestige resets the run.',
    ],
  },
  {
    id: 'hosts-and-stages',
    type: 'article',
    section: 'hosts',
    title: 'Hosts And Stages',
    summary: 'Each stage represents a larger host with escalating complexity. Completing one host lets you advance to the next.',
    keywords: ['host', 'stage', 'advance', 'zones', 'echoes'],
    content: [
      'The campaign features 11 hosts across three conceptual arcs: Micro (1-2), Organism (3-6), and Planetary (7-11).',
      'Every host has health that must be depleted through biomass production and clicking.',
      'Stages 3+ feature multiple zones that unlock sequentially as you compromise the host.',
      'When all zones reach 100% compromise (or the integration meter fills for Stage 11), the host is complete.',
      'After completion, use the stage advance control to move to the next host.',
      'Higher stages introduce new mechanics: defense events, zone unlocking, active attacks, seasonal cycles, rival networks, and more.',
    ],
  },
  {
    id: 'host-zones',
    type: 'article',
    section: 'hosts',
    title: 'Host Zones',
    summary: 'Multi-zone hosts (Stage 3+) require strategic zone-by-zone consumption.',
    keywords: ['zones', 'unlock', 'threshold', 'queen node', 'heartwood'],
    content: [
      'Starting at Stage 3 (The Ant Colony), hosts are divided into multiple zones.',
      'Each zone has its own health pool represented as a percentage of total host health.',
      'Zones unlock when compromise reaches a threshold (e.g., Outer Colony at 0%, Queen Node at 60%).',
      'Damage is applied to the currently active zone. You cannot deal damage to locked zones.',
      'Some zones have special mechanics: Queen Nodes accelerate drain when compromised, Neural zones affect stress levels.',
      'A host is complete when all unlocked zones reach 100% compromise.',
    ],
  },
  {
    id: 'host-echoes',
    type: 'article',
    section: 'hosts',
    title: 'Host Echoes',
    summary: 'Earn permanent bonuses based on how you clear each host.',
    keywords: ['echoes', 'aggressive', 'efficient', 'resilient', 'patient', 'permanent'],
    content: [
      'Host Echoes are permanent bonuses earned the first time you clear each host.',
      'Your playstyle during a host determines which Echo you receive:',
      '  • Aggressive (Predatory Instinct): Clear with high click-to-passive ratio. Grants +5% click multiplier.',
      '  • Efficient (Optimized Metabolism): Balanced approach. Grants +3% passive multiplier.',
      '  • Resilient (Stress Hardening): Survived multiple defense events. Grants +5% defense mitigation.',
      '  • Patient (Dormant Potential): Low click activity. Grants +0.5 max Signal.',
      'Echoes persist across all future runs and can be viewed in the Evolution screen.',
      'You can only earn one Echo per host, but different hosts can have different Echoes.',
    ],
  },
  {
    id: 'prestige-overview',
    type: 'article',
    section: 'prestige',
    title: 'Spore Release',
    summary: 'Spore Release is the prestige system. It will reset the run in exchange for permanent Genetic Memory.',
    keywords: ['prestige', 'spore release', 'reset', 'genetic memory'],
    content: [
      'Prestige resets current-run growth systems like biomass, generators, upgrades, strain choice, and stats.',
      'In exchange, you gain Genetic Memory based on lifetime biomass accumulated during the run.',
      'Genetic Memory provides a permanent production bonus to all future runs.',
      'Prestige also unlocks new strategic options, including the Saprophyte strain.',
      'Genetic Memory stacks from multiple runs up to a cap.',
    ],
  },
  {
    id: 'signal-economy',
    type: 'article',
    section: 'prestige',
    title: 'Signal Economy (Experimental)',
    summary: 'A prestige-layer resource that unlocks at Stage 3 on Run 2+. Signal provides production bonuses and spendable actions.',
    keywords: ['signal', 'coordination', 'vulnerability', 'suppression', 'prestige'],
    content: [
      'Signal unlocks at Stage 3 starting from your second run (after first prestige).',
      'Signal accumulates passively when unlocked and provides a production bonus based on current amount.',
      'Signal has a maximum cap and decays when above a threshold.',
      'Overspending Signal (dropping below penalty threshold) reduces BPS temporarily.',
      'Signal can be spent on powerful actions:',
      '  • Coordination Command: Boosts target tier production for 30 seconds.',
      '  • Vulnerability Window: Increases host damage taken for 30 seconds.',
      '  • Rival Suppression: Pauses rival network activities.',
      'Strain modifiers affect Signal: Symbiote produces more, Parasite has lower cap, Saprophyte decays slower.',
      'Signal economy is implemented but UI exposure is experimental.',
    ],
  },
  {
    id: 'faq-bpc',
    type: 'faq',
    section: 'faq',
    title: 'What do BPC, BPS, STAGE, and LTB mean?',
    summary: 'These are the main shorthand labels used in the interface.',
    keywords: ['bpc', 'bps', 'stage', 'ltb'],
    content: [
      'BPC = Biomass Per Click, BPS = Biomass Per Second, STAGE = your current host tier, and LTB = Lifetime Biomass.',
    ],
  },
  {
    id: 'faq-strain',
    type: 'faq',
    section: 'faq',
    title: 'Why can’t I choose a strain yet?',
    summary: 'Strain selection is locked until the first host is cleared.',
    keywords: ['strain', 'locked', 'first host'],
    content: ['Strain selection becomes available after you consume the first host. Until then, the run stays in its base growth state.'],
  },
  {
    id: 'faq-saprophyte',
    type: 'faq',
    section: 'faq',
    title: 'Why is Saprophyte locked?',
    summary: 'Saprophyte is a prestige-locked strain.',
    keywords: ['saprophyte', 'locked', 'prestige'],
    content: ['Saprophyte is intended to unlock after your first Spore Release. It is not available on a fresh file.'],
  },
  {
    id: 'faq-skills',
    type: 'faq',
    section: 'faq',
    title: 'Why are some skills locked?',
    summary: 'Skills require both stage and stat thresholds.',
    keywords: ['skills', 'locked', 'requirements'],
    content: ['Skills unlock at Stage 3 and also require a minimum rank in one of the three core stats.'],
  },
  {
    id: 'faq-generators',
    type: 'faq',
    section: 'faq',
    title: 'Why are some generator modules locked?',
    summary: 'Higher-tier generators unlock through stage progress.',
    keywords: ['generators', 'locked', 'stage'],
    content: ['Some generator modules require host progression or stage-specific degradation milestones before they can be purchased, even if you can afford them.'],
  },
  {
    id: 'faq-production-drop',
    type: 'faq',
    section: 'faq',
    title: 'Why did my production suddenly drop?',
    summary: 'A host defense event probably triggered.',
    keywords: ['production', 'drop', 'drought', 'beetle'],
    content: ['The most common cause is a host defense event like Drought or Beetle Disruption. Check the host analysis panel and the log.'],
  },
  {
    id: 'faq-host-complete',
    type: 'faq',
    section: 'faq',
    title: 'What happens when I complete a host?',
    summary: 'You can advance to the next stage.',
    keywords: ['host complete', 'advance stage'],
    content: ['When a host reaches zero health, that stage is complete. Use the stage advance control to move to the next host.'],
  },
  {
    id: 'faq-system-logs',
    type: 'faq',
    section: 'faq',
    title: 'What does SYSTEM LOGS do?',
    summary: 'It toggles the observation log footer.',
    keywords: ['system logs', 'observation log'],
    content: ['SYSTEM LOGS shows or hides the observation log panel. On desktop it appears as a footer row at the bottom of the terminal view. On mobile it opens a collapsible card below the hero section. Both display the last 12 log entries with a typewriter effect.'],
  },
  {
    id: 'faq-mutation-points',
    type: 'faq',
    section: 'faq',
    title: 'Why do I have no mutation points left?',
    summary: 'Mutation points are spent permanently for the current run.',
    keywords: ['mutation points', 'spent'],
    content: ['Mutation points are consumed when you raise Virulence, Resilience, or Complexity. They are not refunded until a future prestige reset.'],
  },
  {
    id: 'faq-host-echoes',
    type: 'faq',
    section: 'faq',
    title: 'What are Host Echoes?',
    summary: 'Permanent bonuses earned based on how you clear each host.',
    keywords: ['echoes', 'permanent', 'bonus'],
    content: ['Host Echoes are permanent bonuses you earn the first time you clear each host. Your playstyle determines which Echo you get: Aggressive (clicks), Efficient (balanced), Resilient (survived defenses), or Patient (idle). Echoes persist across all future runs.'],
  },
  {
    id: 'faq-signal',
    type: 'faq',
    section: 'faq',
    title: 'When does Signal unlock?',
    summary: 'Signal is a prestige-layer feature available from Run 2 onward.',
    keywords: ['signal', 'locked', 'prestige', 'run 2'],
    content: ['Signal unlocks at Stage 3 starting from your second run (after first Spore Release). It provides production bonuses and can be spent on powerful actions. Signal is not available on your first run.'],
  },
  {
    id: 'faq-zones-locked',
    type: 'faq',
    section: 'faq',
    title: 'Why are some zones locked?',
    summary: 'Zones unlock as you compromise the host.',
    keywords: ['zones', 'locked', 'unlock', 'threshold'],
    content: ['Multi-zone hosts require you to compromise zones sequentially. Each zone has an unlock threshold based on total host compromise. Focus damage on unlocked zones to progress and reveal deeper zones.'],
  },
  {
    id: 'faq-enzymes',
    type: 'faq',
    section: 'faq',
    title: 'What are Enzyme Reserves?',
    summary: 'Resource for launching Active Attacks (Stage 4+).',
    keywords: ['enzyme', 'reserves', 'active attack'],
    content: ['Enzyme Reserves unlock at Stage 4. They build passively over time and can be spent to launch targeted attacks on specific zones. Active attacks provide temporary BPS bonuses while active.'],
  },
  {
    id: 'faq-countermeasures',
    type: 'faq',
    section: 'faq',
    title: 'How do Countermeasures work?',
    summary: 'Six countermeasures with tiered coverage protect against defense events.',
    keywords: ['countermeasure', 'defense', 'mitigation'],
    content: ['You can equip ONE countermeasure per run. Each provides 70% mitigation (full coverage) for some events and 30% mitigation (partial coverage) for others. Read each countermeasure description carefully to choose the best match for your current host. Resilience adds +5% mitigation per point, capped at 90% total.'],
  },
  {
    id: 'faq-change-countermeasure',
    type: 'faq',
    section: 'faq',
    title: 'Can I change my countermeasure?',
    summary: 'Countermeasures are locked for the entire run once equipped.',
    keywords: ['countermeasure', 'change', 'locked'],
    content: ['Once you equip a countermeasure, it remains locked for the entire run. You cannot switch or unequip it. Choose based on the current host\'s defense profile, or plan ahead for upcoming hosts.'],
  },
]
