import { countermeasureDefinitions, type CountermeasureId } from '../../lib/game'
import type { Enemy } from './enemy.types'

const basicBiomassDrop = (id: string, name: string, description: string, chance: number, biomassReward: number) => ({
  id,
  name,
  description,
  chance,
  biomassReward,
})

const signalDrop = (id: string, name: string, description: string, chance: number, signalReward: number) => ({
  id,
  name,
  description,
  chance,
  signalReward,
})

export const enemyDefinitions: Enemy[] = [
  {
    id: 'carrion-mite',
    name: 'Carrion Mite',
    epithet: 'detritus skimmer',
    description: 'A mat of pale mites scrapes at exposed hyphae before the colony can seal itself.',
    ecology: 'These mites arrive wherever decomposition first softens a surface.',
    counterplay: 'Chitin reinforcement blunts their feeding routes before they multiply.',
    behavior: 'swarmer',
    hostStageMin: 1,
    hostStageMax: 2,
    power: 2.2,
    biomassReward: 14,
    spawnWeight: 10,
    weaknesses: ['chitin-lattice'],
    resistances: ['moisture-buffer'],
    dropTable: [basicBiomassDrop('mite-pulp', 'Mite Pulp', 'Recovered feeding slurry can be reprocessed into biomass.', 0.28, 8)],
  },
  {
    id: 'slug-trail-raider',
    name: 'Slug-Trail Raider',
    epithet: 'moisture thief',
    description: 'A broad mollusk follows the wettest channels of growth and strips them clean.',
    ecology: 'It tracks condensation lines and punishes careless surface spread.',
    counterplay: 'Moisture buffering lets the colony deny the wet edge it feeds on.',
    behavior: 'stealer',
    hostStageMin: 1,
    hostStageMax: 3,
    power: 2.8,
    biomassReward: 18,
    spawnWeight: 8,
    weaknesses: ['moisture-buffer'],
    resistances: ['spore-shield'],
    dropTable: [basicBiomassDrop('trace-salts', 'Trace Salts', 'Mineral residue from the raider can be folded back into growth.', 0.24, 10)],
  },
  {
    id: 'bark-borer',
    name: 'Bark Borer',
    epithet: 'tunnel chewer',
    description: 'A drilling beetle opens dry tunnels through fresh channels and vents the colony to air.',
    ecology: 'It thrives where bark is already soft enough to split but not yet fully collapsed.',
    counterplay: 'Chitin lattices hold fractured tunnels together long enough to drown the boring front.',
    behavior: 'burrower',
    hostStageMin: 2,
    hostStageMax: 3,
    power: 4.2,
    biomassReward: 42,
    spawnWeight: 9,
    weaknesses: ['chitin-lattice'],
    resistances: ['signal-jammer'],
    dropTable: [basicBiomassDrop('borer-frass', 'Borer Frass', 'Ground bark and tissue can be reclaimed by decomposer blooms.', 0.22, 18)],
  },
  {
    id: 'mold-grazer',
    name: 'Mold Grazer',
    epithet: 'surface browser',
    description: 'A soft-bodied browser strips the colony from the surface faster than it can mat together.',
    ecology: 'It follows damp bloom fronts and feeds on newly visible fungal tissue.',
    counterplay: 'Spore shielding hides exposed reproductive surfaces from the grazer.',
    behavior: 'standard',
    hostStageMin: 2,
    hostStageMax: 4,
    power: 4.7,
    biomassReward: 50,
    spawnWeight: 7,
    weaknesses: ['spore-shield'],
    resistances: ['moisture-buffer'],
    dropTable: [basicBiomassDrop('grazed-lattice', 'Grazed Lattice', 'Damaged outer tissue still yields salvageable nutrient pulp.', 0.2, 22)],
  },
  {
    id: 'root-weevil',
    name: 'Root Weevil',
    epithet: 'allelochemical cutter',
    description: 'A root-biting insect forces poison-rich sap back through your newest lines.',
    ecology: 'It nests where living roots still remember how to repel fungal intrusion.',
    counterplay: 'Enzyme suppression keeps root chemistry from turning each bite into a toxin pulse.',
    behavior: 'stealer',
    hostStageMin: 3,
    hostStageMax: 5,
    power: 6.1,
    biomassReward: 76,
    spawnWeight: 8,
    weaknesses: ['enzyme-suppressor'],
    resistances: ['chitin-lattice'],
    dropTable: [basicBiomassDrop('root-nectar', 'Root Nectar', 'Stolen sap can be fermented into fresh biomass.', 0.21, 26)],
  },
  {
    id: 'burrow-vole',
    name: 'Burrow Vole',
    epithet: 'substrate scatterer',
    description: 'A blind tunneler disrupts established cords by overturning whole pockets of substrate.',
    ecology: 'Its migration churns soil faster than a shallow colony can recolonize it.',
    counterplay: 'Thermal regulation keeps deeper layers active while upper channels collapse.',
    behavior: 'burrower',
    hostStageMin: 3,
    hostStageMax: 5,
    power: 6.8,
    biomassReward: 88,
    spawnWeight: 7,
    weaknesses: ['thermal-regulator'],
    resistances: ['signal-jammer'],
    dropTable: [basicBiomassDrop('warm-loam', 'Warm Loam', 'Freshly exposed loam collapses into easy nutrient capture.', 0.18, 32)],
  },
  {
    id: 'shellback-snail',
    name: 'Shellback Snail',
    epithet: 'armored rasp',
    description: 'A hard-shelled grazer rasps along the colony edge and ignores light suppression.',
    ecology: 'Its shell stores moisture and lets it outlast exposed mycelial fans.',
    counterplay: 'Thermal gradients crack its reserve shell faster than direct pressure does.',
    behavior: 'armored',
    hostStageMin: 4,
    hostStageMax: 6,
    power: 8.3,
    biomassReward: 118,
    spawnWeight: 6,
    weaknesses: ['thermal-regulator'],
    resistances: ['moisture-buffer'],
    dropTable: [basicBiomassDrop('shell-calcium', 'Shell Calcium', 'Mineral-rich shell shards reinforce nearby feeder mats.', 0.18, 40)],
  },
  {
    id: 'truffle-hog',
    name: 'Truffle Hog',
    epithet: 'subsurface raider',
    description: 'A rooting mammal tears up nutrient knots and exposes fruiting tissue to air.',
    ecology: 'It follows the same rich scent signatures that mark your deepest caches.',
    counterplay: 'Signal jamming muddies the scent trail before the animal can localize it.',
    behavior: 'stealer',
    hostStageMin: 4,
    hostStageMax: 6,
    power: 9.1,
    biomassReward: (state) => 112 + state.currentStage * 10,
    spawnWeight: 6,
    weaknesses: ['signal-jammer'],
    resistances: ['spore-shield'],
    dropTable: [basicBiomassDrop('upturned-riches', 'Upturned Riches', 'Dislodged nutrient masses are easy to absorb after the raid.', 0.24, 44)],
  },
  {
    id: 'nestbreaker-ant',
    name: 'Nestbreaker Ant Column',
    epithet: 'marching severance',
    description: 'An ant column cuts through exposed connective tissue in disciplined waves.',
    ecology: 'Their coordinated bite patterns make them far more dangerous than their mass suggests.',
    counterplay: 'Chitin lattices spread the shock of each severed strand across the network.',
    behavior: 'swarmer',
    hostStageMin: 4,
    hostStageMax: 7,
    power: 10.4,
    biomassReward: 150,
    spawnWeight: 7,
    weaknesses: ['chitin-lattice'],
    resistances: ['signal-jammer'],
    dropTable: [basicBiomassDrop('acid-glands', 'Acid Glands', 'Ant chemistry can be inverted into aggressive digestive yield.', 0.18, 52)],
  },
  {
    id: 'hedge-shrew',
    name: 'Hedge Shrew',
    epithet: 'quick snout intrusion',
    description: 'A small insectivore collapses active fronts before the colony can harden them.',
    ecology: 'It thrives in dense litter where fungal signatures gather too close together.',
    counterplay: 'Spore shielding blurs the edge between live fruiting tissue and dead substrate.',
    behavior: 'adapting',
    hostStageMin: 5,
    hostStageMax: 6,
    power: 11.6,
    biomassReward: 176,
    spawnWeight: 5,
    weaknesses: ['spore-shield'],
    resistances: ['thermal-regulator'],
    dropTable: [basicBiomassDrop('whisker-sensors', 'Whisker Sensors', 'Fine sensory tissue yields a map of nearby pressure channels.', 0.14, 60)],
  },
  {
    id: 'carrion-rook',
    name: 'Carrion Rook',
    epithet: 'aerial plucker',
    description: 'A black-feathered scavenger tears out fruiting crowns and drags them skyward.',
    ecology: 'It follows visible bloom density and arrives when the colony becomes too obvious.',
    counterplay: 'Spore shielding keeps the visible crown thin enough to survive the first pass.',
    behavior: 'sacrificial',
    hostStageMin: 5,
    hostStageMax: 7,
    power: 13.1,
    biomassReward: 210,
    spawnWeight: 4,
    weaknesses: ['spore-shield'],
    resistances: ['moisture-buffer'],
    dropTable: [basicBiomassDrop('black-feather-resin', 'Black Feather Resin', 'Tar-rich residue compresses into dense growth stock.', 0.2, 68)],
  },
  {
    id: 'ash-beetle-host',
    name: 'Ash Beetle Host',
    epithet: 'burnt-carapace vector',
    description: 'A beetle colony arrives carrying hostile microbes in every scored trench.',
    ecology: 'It marks dying wood and converts partial collapse into a second front of infection.',
    counterplay: 'Enzyme suppression chokes the microbial bloom before the beetles can seed it.',
    behavior: 'armored',
    hostStageMin: 6,
    hostStageMax: 7,
    power: 14.7,
    biomassReward: 245,
    spawnWeight: 5,
    weaknesses: ['enzyme-suppressor'],
    resistances: ['chitin-lattice'],
    dropTable: [basicBiomassDrop('charred-frass', 'Charred Frass', 'Burnt microbial mulch collapses into concentrated biomass.', 0.17, 74)],
  },
  {
    id: 'feral-boar',
    name: 'Feral Boar',
    epithet: 'forest plow',
    description: 'A heavy grazer tears trenches through the mycelial bed and leaves whole fronts exposed.',
    ecology: 'It arrives when the forest itself begins to smell like overripe decay.',
    counterplay: 'Signal masking throws its rooting patterns off before it reaches the densest beds.',
    behavior: 'burrower',
    hostStageMin: 6,
    hostStageMax: 8,
    power: (state) => 15.2 + state.currentStage * 0.6,
    biomassReward: 300,
    spawnWeight: 4,
    weaknesses: ['signal-jammer'],
    resistances: ['moisture-buffer'],
    dropTable: [basicBiomassDrop('rooted-slurry', 'Rooted Slurry', 'Turned soil and fungal paste absorb back into the bed quickly.', 0.2, 82)],
  },
  {
    id: 'rootfire-stag',
    name: 'Rootfire Stag',
    epithet: 'heat-tracking grazer',
    description: 'A massive herbivore follows metabolic heat through roots and strips out every warm channel.',
    ecology: 'Its antlers crack lignified barriers the colony was already softening.',
    counterplay: 'Thermal regulators flatten the heat plume it depends on for tracking.',
    behavior: 'adapting',
    hostStageMin: 6,
    hostStageMax: 8,
    power: 18.4,
    biomassReward: 360,
    spawnWeight: 3,
    weaknesses: ['thermal-regulator'],
    resistances: ['signal-jammer'],
    dropTable: [basicBiomassDrop('antler-ash', 'Antler Ash', 'Powdered antler channels mineral density back into deep growth.', 0.14, 96)],
  },
  {
    id: 'apex-badger',
    name: 'Apex Badger',
    epithet: 'den breaker',
    description: 'A biome-level digger ruptures layered chambers faster than surface growth can hide them.',
    ecology: 'It is drawn to stable fungal dominance the way a predator is drawn to a den.',
    counterplay: 'Chitin lattices turn catastrophic cave-ins into localized collapses.',
    behavior: 'armored',
    hostStageMin: 7,
    hostStageMax: 8,
    power: 21.5,
    biomassReward: (state) => 380 + state.stats.resilience * 18,
    spawnWeight: 3,
    weaknesses: ['chitin-lattice'],
    resistances: ['spore-shield'],
    dropTable: [basicBiomassDrop('den-fat', 'Den Fat', 'Nutrient-rich reserves from the den collapse into slow-release biomass.', 0.18, 110)],
  },
  {
    id: 'flood-heron',
    name: 'Flood Heron',
    epithet: 'watershed spear',
    description: 'A patient hunter stands at the margin and extracts fruiting bodies from runoff lines.',
    ecology: 'It appears where water already carries spores farther than roots ever could.',
    counterplay: 'Moisture buffering denies the standing pools that let it hunt in place.',
    behavior: 'sacrificial',
    hostStageMin: 7,
    hostStageMax: 8,
    power: 23.2,
    biomassReward: 520,
    spawnWeight: 2,
    weaknesses: ['moisture-buffer'],
    resistances: ['thermal-regulator'],
    dropTable: [basicBiomassDrop('reed-marsh', 'Reed Marsh', 'Flooded detritus forms a rich slurry once reclaimed.', 0.16, 126)],
  },
  {
    id: 'biosphere-white',
    name: 'Biosphere White',
    epithet: 'ecological antibody',
    description: 'A legendary bloom of coordinated resistance rises from the whole ecosystem at once.',
    ecology: 'This is not a single animal but a synchronized recoil of every surviving niche.',
    counterplay: 'Only layered signaling discipline can keep the colony from becoming the obvious target.',
    behavior: 'adapting',
    hostStageMin: 8,
    hostStageMax: null,
    power: (state) => 24 + state.stats.complexity * 0.8 + state.prestigeCount * 1.1,
    biomassReward: (state) => 720 + state.currentStage * 40 + state.stats.complexity * 20,
    spawnWeight: 1,
    weaknesses: ['signal-jammer'],
    resistances: ['enzyme-suppressor'],
    dropTable: [
      basicBiomassDrop('white-spore-mass', 'White Spore Mass', 'Collapsed global bloom matter feeds the colony for a final surge.', 0.22, 180),
      signalDrop('biosphere-echo', 'Biosphere Echo', 'A shard of the wider response can be routed into dormant signaling tissue.', 0.1, 0.8),
    ],
  },
]

export function getEnemyById(enemyId: string): Enemy | null {
  return enemyDefinitions.find((enemy) => enemy.id === enemyId) ?? null
}

export function getCountermeasureName(countermeasureId: CountermeasureId): string {
  return countermeasureDefinitions.find((countermeasure) => countermeasure.id === countermeasureId)?.name ?? countermeasureId
}
